In [1]:
import numpy as np

In [2]:
# Sigmoid Activation Function
# Formula: sigmoid(x)= 1 / (1 + exp(-x))

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([-3, -1, 0, 1, 3])
print(sigmoid(x))

[0.04742587 0.26894142 0.5        0.73105858 0.95257413]


In [3]:
# Tanh Activation Function
# Formula: tanh(x) = (exp(x) - exp(-x)) / (exp(x) + exp(-x))

def tanh(x):
    return np.tanh(x)

x = np.array([-3, -1, 0, 1, 3])
print(tanh(x))

[-0.99505475 -0.76159416  0.          0.76159416  0.99505475]


In [4]:
# ReLU Activation Function
# Formula: relu(x) = max(0,x)

def relu(x):
    return np.maximum(0, x)

x = np.array([-3, -1, 0, 1, 3])
print(relu(x))

[0 0 0 1 3]


In [5]:
# LeakyRelu Activation Function
# Formula: leaky_relu(x) = x if x > 0 else alpha*x (alpha=0.01)

def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

x = np.array([-3, -1, 0, 1, 3])
print(leaky_relu(x))

[-0.03 -0.01  0.    1.    3.  ]


In [6]:
# Softmax Activation Function
# Formula: softmax(x) = exp(x) / sum(exp(x))

import numpy as np

def softmax(x):
    e = np.exp(x - np.max(x))  # numerical stability
    return e / e.sum()

x = np.array([1.0, 2.0, 3.0])
print(softmax(x))

[0.09003057 0.24472847 0.66524096]
